echo "  Creating user '$GITEA_DB_USER' and database '$GITEA_DB_DATABASE'"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $GITEA_DB_USER WITH ENCRYPTED PASSWORD '$GITEA_DB_PASSWORD';
    CREATE DATABASE $GITEA_DB_DATABASE;
    GRANT ALL PRIVILEGES ON DATABASE $GITEA_DB_DATABASE TO $GITEA_DB_USER;
EOSQL
